In [2]:
import sys
print(sys.executable)

/Users/raymondfurtado/Desktop/ML project End to End/venv/bin/python

In [5]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [6]:
df = pd.read_csv('stud.csv')

In [7]:
df.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [8]:
df = df.rename(columns = {'race_ethnicity': 'race/ethnicity', 'parental_level_of_education': 'parental level of education', 'test_preparation_course': 'test preparation course','lunch':'lunch type'})

In [9]:
df.head()

   gender race/ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [11]:
#  Preparing X and Y variables 
# The goal here is to predict the math score of the students. So, we will set the math score as our target variable and the rest of the columns as our features.

X = df.drop('math_score',axis=1)
y = df['math_score']

In [12]:
X.head()

   gender race/ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [15]:
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math_score, dtype: int64

In [16]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch type                   1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   reading_score                1000 non-null   int64
 6   writing_score                1000 non-null   int64
dtypes: int64(2), str(5)
memory usage: 54.8 KB

In [18]:
categorical_cols = X.select_dtypes(include=['str']).columns
for col in categorical_cols:
    print(f"unique values in {col} : {X[col].unique()}")

unique values in gender : <StringArray>
['female', 'male']
Length: 2, dtype: str
unique values in race/ethnicity : <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
unique values in parental level of education : <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
unique values in lunch type : <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
unique values in test preparation course : <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [19]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [24]:
# Create column transformer with 3 types of transformers

num_feature = X.select_dtypes(exclude=['str']).columns
cat_feature = X.select_dtypes(include=['str']).columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    [
     ("OneHotEncoder", categorical_transformer, cat_feature),
     ("StandardScaler", numeric_transformer, num_feature)
    ]
)

In [25]:
X = preprocessor.fit_transform(X)

In [30]:
X

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [31]:
# Create a train-test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 19), (200, 19), (800,), (200,))

In [29]:
X.shape

(1000, 19)

In [32]:
# Creating a function to evaluate the model performance 

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [36]:
models = {
    "Liner Regression" : LinearRegression(),
    "Lasso" : Lasso(),
    "Ridge" : Ridge(),
    "K - Neighbors Regressor" : KNeighborsRegressor(),
    "Decision Tree" : DecisionTreeRegressor(),
    "Random Forest Regressor" : RandomForestRegressor(),
    "XGBRegressor" : XGBRegressor(),
    "CatBoostRegressor" : CatBoostRegressor(verbose=False),
    "AdaBoostRegressor" : AdaBoostRegressor()
}

model_list = []
r2_list = []


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train Model

    y_train_pred = model.predict(X_train) # Make Prediction
    y_test_pred = model.predict(X_test) # Make Prediction

    # Evaluate Train and Test dataset 
    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Liner Regression
Model performance for Training set
- Root Mean Squared Error: 5.3231
- Mean Absolute Error: 4.2667
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3940
- Mean Absolute Error: 4.2148
- R2 Score: 0.8804
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.5938
- Mean Absolute Error: 5.2063
- R2 Score: 0.8071
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5197
- Mean Absolute Error: 5.1579
- R2 Score: 0.8253
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 5.3233
- Mean Absolute Error: 4.2650
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3904
- Mean Absolute Error: 4.2111
- R2 Score: 0.8806
===================================


K - Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 5.7172
- Mean Absolute Error: 4.5270
- R2 Score: 0.8550
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.2553
- Mean Absolute Error: 5.6280
- R2 Score: 0.7837
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.2795
- Mean Absolute Error: 0.0187
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.4377
- Mean Absolute Error: 5.9400
- R2 Score: 0.7727
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 2.2634
- Mean Absolute Error: 1.7947
- R2 Score: 0.9773
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.9599
- Mean Absolute Error: 4.6337
- R2 Score: 0.8540
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 1.0073
- Mean Absolute Error: 0.6875
- R2 Score: 0.9955
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.4733
- Mean Absolute Error: 5.0577
- R2 Score: 0.8278
===================================


CatBoostRegressor
Model performance for Training set
- Root Mean Squared Error: 3.0427
- Mean Absolute Error: 2.4054
- R2 Score: 0.9589
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0086
- Mean Absolute Error: 4.6125
- R2 Score: 0.8516
===================================


AdaBoostRegressor
Model performance for Training set
- Root Mean Squared Error: 5.8258
- Mean Absolute Error: 4.7393
- R2 Score: 0.8495
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0621
- Mean Absolute Error: 4.6718
- R2 Score: 0.8490
===================================

In [37]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
2                    Ridge  0.880593
0         Liner Regression  0.880433
5  Random Forest Regressor  0.854027
7        CatBoostRegressor  0.851632
8        AdaBoostRegressor  0.848982
6             XGBRegressor  0.827797
1                    Lasso  0.825320
3  K - Neighbors Regressor  0.783681
4            Decision Tree  0.772662

In [38]:
lin_model = LinearRegression(fit_intercept=True)
lin_model = lin_model.fit(X_train, y_train)
y_pred = lin_model.predict(X_test)
score = r2_score(y_test, y_pred)*100
print(" Accuracy of the model is %.2f" %score)

 Accuracy of the model is 88.04

In [39]:
# Difference Between Actual and Predicted Values

pred_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred, 'Difference': y_test - y_pred})
pred_df

     Actual  Predicted  Difference
521      91  76.387970   14.612030
737      53  58.885970   -5.885970
740      80  76.990265    3.009735
660      74  76.851804   -2.851804
411      84  87.627378   -3.627378
..      ...        ...         ...
408      52  43.409149    8.590851
332      62  62.152214   -0.152214
208      74  67.888395    6.111605
613      65  67.022287   -2.022287
78       61  62.345132   -1.345132

[200 rows x 3 columns]